export const AppContent = {
  app: "React app",
  ok: "Ok",
  cancel: "Cancel",
  save: "Save",
  add: "Add",
  delete: "Delete",
  update: "Update",
  login: "Login",
  reset: "Reset",
  welcomeText: "Welcome to React app",
  forgotPassword: "Forgot password",
  loginSubtitle: "New user?",
  registerSubtitle: "Already have an account?",
  createAccount: "Create account",
  gotoHome: "Go to home",
  pageNotFoundTitle: "Sorry, Page Not Found!",
  pageNotFoundContent:
    "Sorry, we couldn’t find the page you’re looking for. Perhaps you’ve mistyped the URL? Be sure to check your spelling.",
};
