export const AppContent = {
  app: "React app",
  ok: "Ok",
  cancel: "Cancel",
  save: "Save",
  add: "Add",
  delete: "Delete",
  update: "Update",
  login: "Login",
  reset: "Reset",
  welcomeText: "Welcome to React app",
  forgotPassword: "Forgot password",
  loginSubtitle: "New user?",
  registerSubtitle: "Already have an account?",
  createAccount: "Create account",
};
